-- ============================================================
-- DEV-EMAIL-01.1
-- Persistent Email Queue
--
-- Objetivo:
-- Crear la capa persistente que representa las obligaciones
-- de envío de correo de Nook, desacoplando los eventos de
-- negocio del proveedor de email (Resend).
--
-- Alcance de este DEV:
-- - Persistencia de emails pendientes/enviados/fallidos.
-- - Prioridades.
-- - Idempotencia.
-- - Reintentos.
-- - Trazabilidad con proveedor.
-- - Preparación para procesamiento concurrente.
--
-- Este DEV NO implementa todavía el dispatcher.
-- ============================================================


CREATE TABLE IF NOT EXISTS public.email_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- ----------------------------------------------------------
  -- Destinatario / contexto
  -- ----------------------------------------------------------

  customer_id bigint NULL
    REFERENCES public.clientes(id)
    ON DELETE SET NULL,

  recipient_email text NOT NULL,

  email_type text NOT NULL,

  -- Payload necesario para reconstruir el correo al momento
  -- del despacho.
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,


  -- ----------------------------------------------------------
  -- Prioridad
  --
  -- 0 = CRITICAL
  -- 1 = TRANSACTIONAL
  -- 2 = TIME_SENSITIVE_CRM
  -- 3 = CRM
  -- ----------------------------------------------------------

  priority smallint NOT NULL DEFAULT 3,


  -- ----------------------------------------------------------
  -- Estado
  --
  -- PENDING    : esperando despacho/reintento
  -- PROCESSING : tomado temporalmente por un dispatcher
  -- SENT       : aceptado exitosamente por proveedor
  -- FAILED     : agotó política de reintentos / error terminal
  -- CANCELLED  : envío descartado intencionalmente
  -- ----------------------------------------------------------

  status text NOT NULL DEFAULT 'PENDING',


  -- ----------------------------------------------------------
  -- Idempotencia
  --
  -- Una obligación lógica de envío debe tener una key única.
  --
  -- Ejemplos futuros:
  -- register-verification:<customer_id>:<token>
  -- reward-expiring:<reward_id>
  -- ----------------------------------------------------------

  idempotency_key text NOT NULL,


  -- ----------------------------------------------------------
  -- Referencia al evento que originó el correo
  -- ----------------------------------------------------------

  source_type text NULL,
  source_reference text NULL,


  -- ----------------------------------------------------------
  -- Reintentos
  -- ----------------------------------------------------------

  attempt_count integer NOT NULL DEFAULT 0,

  max_attempts integer NOT NULL DEFAULT 5,

  last_attempt_at timestamptz NULL,

  next_attempt_at timestamptz NULL,

  last_error text NULL,


  -- ----------------------------------------------------------
  -- Lock de procesamiento
  --
  -- Se utilizará posteriormente para evitar que dos
  -- dispatchers procesen el mismo correo simultáneamente.
  -- ----------------------------------------------------------

  locked_at timestamptz NULL,

  locked_by text NULL,


  -- ----------------------------------------------------------
  -- Proveedor
  -- ----------------------------------------------------------

  provider text NOT NULL DEFAULT 'resend',

  provider_message_id text NULL,


  -- ----------------------------------------------------------
  -- Ciclo de vida
  -- ----------------------------------------------------------

  sent_at timestamptz NULL,

  cancelled_at timestamptz NULL,

  created_at timestamptz NOT NULL DEFAULT now(),

  updated_at timestamptz NOT NULL DEFAULT now(),


  -- ----------------------------------------------------------
  -- Validaciones
  -- ----------------------------------------------------------

  CONSTRAINT email_queue_recipient_email_not_blank
    CHECK (length(trim(recipient_email)) > 0),

  CONSTRAINT email_queue_email_type_not_blank
    CHECK (length(trim(email_type)) > 0),

  CONSTRAINT email_queue_idempotency_key_not_blank
    CHECK (length(trim(idempotency_key)) > 0),

  CONSTRAINT email_queue_priority_valid
    CHECK (priority IN (0, 1, 2, 3)),

  CONSTRAINT email_queue_status_valid
    CHECK (
      status IN (
        'PENDING',
        'PROCESSING',
        'SENT',
        'FAILED',
        'CANCELLED'
      )
    ),

  CONSTRAINT email_queue_attempt_count_valid
    CHECK (attempt_count >= 0),

  CONSTRAINT email_queue_max_attempts_valid
    CHECK (max_attempts > 0),

  CONSTRAINT email_queue_attempts_within_limit
    CHECK (attempt_count <= max_attempts)
);


-- ============================================================
-- Idempotencia
-- ============================================================

CREATE UNIQUE INDEX IF NOT EXISTS uq_email_queue_idempotency_key
  ON public.email_queue (idempotency_key);


-- ============================================================
-- Índice principal futuro del dispatcher
--
-- Permite encontrar:
-- 1. Emails pendientes
-- 2. Cuyo retry ya corresponde
-- 3. Ordenados posteriormente por prioridad/antigüedad
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_email_queue_dispatch
  ON public.email_queue (
    status,
    priority,
    next_attempt_at,
    created_at
  );


-- ============================================================
-- Trazabilidad por cliente
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_email_queue_customer
  ON public.email_queue (
    customer_id,
    created_at DESC
  );


-- ============================================================
-- Observabilidad por tipo
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_email_queue_type
  ON public.email_queue (
    email_type,
    created_at DESC
  );


-- ============================================================
-- Referencia de negocio
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_email_queue_source
  ON public.email_queue (
    source_type,
    source_reference
  );


-- ============================================================
-- updated_at automático
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_email_queue_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;


DROP TRIGGER IF EXISTS trg_email_queue_updated_at
  ON public.email_queue;


CREATE TRIGGER trg_email_queue_updated_at
BEFORE UPDATE ON public.email_queue
FOR EACH ROW
EXECUTE FUNCTION public.set_email_queue_updated_at();


-- ============================================================
-- Seguridad
--
-- No exponemos la cola directamente al cliente web.
-- El acceso operacional se realizará mediante backend /
-- service role.
-- ============================================================

ALTER TABLE public.email_queue ENABLE ROW LEVEL SECURITY;


COMMENT ON TABLE public.email_queue IS
  'Persistent Nook email outbox/queue. Stores email obligations independently from the email provider.';

COMMENT ON COLUMN public.email_queue.priority IS
  '0=CRITICAL, 1=TRANSACTIONAL, 2=TIME_SENSITIVE_CRM, 3=CRM';

COMMENT ON COLUMN public.email_queue.idempotency_key IS
  'Unique logical identifier preventing duplicate email obligations.';