-- DEV-CASH-01
-- Composición física de efectivo en apertura y cierre de caja.
--
-- Principios:
-- 1. opening_amount y counted_cash_amount continúan siendo los totales canónicos.
-- 2. La composición física se persiste como snapshot independiente
--    para OPENING y CLOSING.
-- 3. Los totales se calculan en base de datos desde la composición recibida.
-- 4. Apertura + snapshot y cierre + snapshot son operaciones atómicas.
-- 5. Acceso restringido a service_role, consistente con el hardening actual.

create table public.cash_register_cash_counts (
    id bigint generated by default as identity primary key,
    cash_register_session_id bigint not null
        references public.cash_register_sessions(id),
    count_type text not null,
    denomination integer not null,
    quantity integer not null,
    subtotal integer generated always as (denomination * quantity) stored,
    created_at timestamptz not null default now(),

    constraint cash_register_cash_counts_count_type_check
        check (count_type in ('OPENING', 'CLOSING')),

    constraint cash_register_cash_counts_denomination_check
        check (
            denomination in (
                20000,
                10000,
                5000,
                2000,
                1000,
                500,
                100,
                50,
                10
            )
        ),

    constraint cash_register_cash_counts_quantity_check
        check (quantity >= 0),

    constraint cash_register_cash_counts_unique_snapshot_row
        unique (
            cash_register_session_id,
            count_type,
            denomination
        )
);

create index idx_cash_register_cash_counts_session
    on public.cash_register_cash_counts (
        cash_register_session_id,
        count_type
    );

alter table public.cash_register_cash_counts
    enable row level security;

revoke all
on table public.cash_register_cash_counts
from public, anon, authenticated;

grant select, insert
on table public.cash_register_cash_counts
to service_role;

revoke all
on sequence public.cash_register_cash_counts_id_seq
from public, anon, authenticated;

grant usage, select
on sequence public.cash_register_cash_counts_id_seq
to service_role;


create or replace function public.calculate_cash_count_total(
    p_cash_count jsonb
)
returns integer
language plpgsql
as $function$
declare
    v_expected_denominations integer[] :=
        array[20000, 10000, 5000, 2000, 1000, 500, 100, 50, 10];

    v_item jsonb;
    v_denomination integer;
    v_quantity integer;
    v_total bigint := 0;
    v_seen_denominations integer[] := array[]::integer[];
begin
    if p_cash_count is null
       or jsonb_typeof(p_cash_count) <> 'array'
    then
        raise exception
            'La composición de efectivo no es válida.';
    end if;

    if jsonb_array_length(p_cash_count)
       <> array_length(v_expected_denominations, 1)
    then
        raise exception
            'La composición debe incluir todas las denominaciones de efectivo.';
    end if;

    for v_item in
        select value
        from jsonb_array_elements(p_cash_count)
    loop
        if jsonb_typeof(v_item) <> 'object'
           or not (v_item ? 'denomination')
           or not (v_item ? 'quantity')
        then
            raise exception
                'La composición de efectivo contiene un registro inválido.';
        end if;

        if jsonb_typeof(v_item -> 'denomination') <> 'number'
           or jsonb_typeof(v_item -> 'quantity') <> 'number'
        then
            raise exception
                'Las denominaciones y cantidades deben ser números enteros.';
        end if;

        if (v_item ->> 'denomination') !~ '^[0-9]+$'
           or (v_item ->> 'quantity') !~ '^[0-9]+$'
        then
            raise exception
                'Las denominaciones y cantidades deben ser números enteros mayores o iguales a cero.';
        end if;

        v_denomination := (v_item ->> 'denomination')::integer;
        v_quantity := (v_item ->> 'quantity')::integer;

        if not (v_denomination = any(v_expected_denominations)) then
            raise exception
                'La composición contiene una denominación no permitida.';
        end if;

        if v_denomination = any(v_seen_denominations) then
            raise exception
                'La composición contiene denominaciones duplicadas.';
        end if;

        v_seen_denominations :=
            array_append(v_seen_denominations, v_denomination);

        v_total :=
            v_total
            + (v_denomination::bigint * v_quantity::bigint);
    end loop;

    if not (
        v_seen_denominations @> v_expected_denominations
        and v_expected_denominations @> v_seen_denominations
    ) then
        raise exception
            'La composición debe incluir todas las denominaciones de efectivo.';
    end if;

    if v_total > 2147483647 then
        raise exception
            'El total contado excede el rango permitido.';
    end if;

    return v_total::integer;
end;
$function$;

revoke all
on function public.calculate_cash_count_total(jsonb)
from public, anon, authenticated;

grant execute
on function public.calculate_cash_count_total(jsonb)
to service_role;


create or replace function public.open_cash_register_session(
    p_cash_count jsonb,
    p_opening_notes text default null,
    p_opened_by_role text default null
)
returns jsonb
language plpgsql
as $function$
declare
    v_opening_amount integer;
    v_opening_notes text;
    v_opened_by_role text;
    v_session_id bigint;
    v_opened_at timestamptz;
    v_item jsonb;
begin
    v_opening_amount :=
        public.calculate_cash_count_total(p_cash_count);

    v_opening_notes :=
        nullif(trim(coalesce(p_opening_notes, '')), '');

    v_opened_by_role :=
        nullif(trim(coalesce(p_opened_by_role, '')), '');

    if v_opened_by_role is null then
        raise exception
            'No fue posible identificar al responsable de la apertura.';
    end if;

    begin
        insert into public.cash_register_sessions (
            status,
            opened_by_role,
            opening_amount,
            opening_notes
        )
        values (
            'OPEN',
            v_opened_by_role,
            v_opening_amount,
            v_opening_notes
        )
        returning
            id,
            opened_at
        into
            v_session_id,
            v_opened_at;
    exception
        when unique_violation then
            raise exception
                'Ya existe una caja abierta.'
                using errcode = '23505';
    end;

    insert into public.cash_register_cash_counts (
        cash_register_session_id,
        count_type,
        denomination,
        quantity
    )
    select
        v_session_id,
        'OPENING',
        (item ->> 'denomination')::integer,
        (item ->> 'quantity')::integer
    from jsonb_array_elements(p_cash_count) as item;

    return jsonb_build_object(
        'id',
        v_session_id,

        'status',
        'OPEN',

        'opened_at',
        v_opened_at,

        'opened_by_role',
        v_opened_by_role,

        'opening_amount',
        v_opening_amount,

        'opening_notes',
        v_opening_notes
    );
end;
$function$;

revoke all
on function public.open_cash_register_session(jsonb, text, text)
from public, anon, authenticated;

grant execute
on function public.open_cash_register_session(jsonb, text, text)
to service_role;


create or replace function public.close_cash_register_session_with_count(
    p_cash_register_session_id bigint,
    p_cash_count jsonb,
    p_closing_notes text default null,
    p_closed_by_role text default null
)
returns jsonb
language plpgsql
as $function$
declare
    v_session_status text;
    v_opening_amount integer;

    v_cash_sales_amount bigint := 0;
    v_cash_sales_count bigint := 0;

    v_cash_in_amount bigint := 0;
    v_cash_in_count bigint := 0;

    v_cash_out_amount bigint := 0;
    v_cash_out_count bigint := 0;

    v_expected_cash_amount bigint := 0;
    v_counted_cash_amount integer;
    v_cash_difference bigint := 0;

    v_closing_notes text;
    v_closed_by_role text;
    v_closed_at timestamptz;
    v_item jsonb;
begin
    if p_cash_register_session_id is null then
        raise exception
            'No se indicó una sesión de caja.';
    end if;

    v_counted_cash_amount :=
        public.calculate_cash_count_total(p_cash_count);

    v_closing_notes :=
        nullif(trim(coalesce(p_closing_notes, '')), '');

    v_closed_by_role :=
        nullif(trim(coalesce(p_closed_by_role, '')), '');

    if v_closed_by_role is null then
        raise exception
            'No fue posible identificar al responsable del cierre.';
    end if;

    select
        status,
        opening_amount
    into
        v_session_status,
        v_opening_amount
    from public.cash_register_sessions
    where id = p_cash_register_session_id
    for update;

    if not found then
        raise exception
            'La sesión de caja no existe.';
    end if;

    if v_session_status <> 'OPEN' then
        raise exception
            'La caja ya se encuentra cerrada.';
    end if;

    select
        coalesce(sum(total), 0),
        count(*)
    into
        v_cash_sales_amount,
        v_cash_sales_count
    from public.sales
    where cash_register_session_id = p_cash_register_session_id
      and lower(trim(payment_method)) = 'efectivo'
      and status = 'confirmed'
      and payment_status = 'paid';

    select
        coalesce(sum(amount), 0),
        count(*)
    into
        v_cash_in_amount,
        v_cash_in_count
    from public.cash_register_movements
    where cash_register_session_id = p_cash_register_session_id
      and movement_type = 'CASH_IN';

    select
        coalesce(sum(amount), 0),
        count(*)
    into
        v_cash_out_amount,
        v_cash_out_count
    from public.cash_register_movements
    where cash_register_session_id = p_cash_register_session_id
      and movement_type = 'CASH_OUT';

    v_expected_cash_amount :=
        coalesce(v_opening_amount, 0)
        + v_cash_sales_amount
        + v_cash_in_amount
        - v_cash_out_amount;

    v_cash_difference :=
        v_counted_cash_amount
        - v_expected_cash_amount;

    if v_cash_difference <> 0
       and v_closing_notes is null
    then
        raise exception
            'Debes ingresar una observación cuando exista una diferencia de caja.';
    end if;

    if v_expected_cash_amount < -2147483648
       or v_expected_cash_amount > 2147483647
       or v_cash_difference < -2147483648
       or v_cash_difference > 2147483647
    then
        raise exception
            'Los montos calculados exceden el rango permitido.';
    end if;

    /*
     * El snapshot se escribe antes del UPDATE, pero forma parte de la
     * misma transacción. Cualquier error posterior revierte ambas cosas.
     */
    insert into public.cash_register_cash_counts (
        cash_register_session_id,
        count_type,
        denomination,
        quantity
    )
    select
        p_cash_register_session_id,
        'CLOSING',
        (item ->> 'denomination')::integer,
        (item ->> 'quantity')::integer
    from jsonb_array_elements(p_cash_count) as item;

    v_closed_at := now();

    update public.cash_register_sessions
    set
        status = 'CLOSED',
        closed_at = v_closed_at,
        closed_by_role = v_closed_by_role,
        expected_cash_amount = v_expected_cash_amount::integer,
        counted_cash_amount = v_counted_cash_amount,
        cash_difference = v_cash_difference::integer,
        closing_notes = v_closing_notes,
        updated_at = v_closed_at
    where id = p_cash_register_session_id;

    return jsonb_build_object(
        'id',
        p_cash_register_session_id,

        'status',
        'CLOSED',

        'opening_amount',
        coalesce(v_opening_amount, 0),

        'cash_sales_amount',
        v_cash_sales_amount,

        'cash_sales_count',
        v_cash_sales_count,

        'cash_in_amount',
        v_cash_in_amount,

        'cash_in_count',
        v_cash_in_count,

        'cash_out_amount',
        v_cash_out_amount,

        'cash_out_count',
        v_cash_out_count,

        'expected_cash_amount',
        v_expected_cash_amount,

        'counted_cash_amount',
        v_counted_cash_amount,

        'cash_difference',
        v_cash_difference,

        'closing_notes',
        v_closing_notes,

        'closed_by_role',
        v_closed_by_role,

        'closed_at',
        v_closed_at
    );
end;
$function$;

revoke all
on function public.close_cash_register_session_with_count(bigint, jsonb, text, text)
from public, anon, authenticated;

grant execute
on function public.close_cash_register_session_with_count(bigint, jsonb, text, text)
to service_role;